"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&fwg$gsng36t@0$#f*w5*l2b1^31=6%8l8d+il(qui&pb20$!!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djmoney',
    'appShop',
    'appSettings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_HEADER": "Магазин", # это для заголовка в админке
    "SITE_SUBHEADER": "Администрирование", # это для подзаголовка в админке
    "SITE_DROPDOWN": [ # это для выпадающего меню в админке (это для ссылки на сайт)
        {
            "icon": "Shopping_Bag_Speed", # это для иконки в выпадающем меню 
            "title": "Ozon", # это для текста в выпадающем меню
            "link": "https://www.ozon.ru", # это для ссылки в выпадающем меню 
        },
    ],
    "SIDEBAR": { # это для левого меню в админке
        "show_search": True, # это для поиска в админке 
        "command_search": True, # это для поиска в админке
        "show_all_applications": True, # это для поиска в админке
        "navigation": [ # это для левого меню в админке
            {
                "title": "Пользователи и группы", # это для текста в левом меню
                "separator": True, # это для разделителя в левом меню
                "collapsible": True, # это для скрытия в левом меню 
                "items" : [ # это для левого меню в админке
                    {
                        "title": "Доступы", # это для текста в левом меню
                        "icon": "Ad_Group", # это для иконки в левом меню
                        "link": reverse_lazy("admin:auth_group_changelist") # это для ссылки в левом меню
                    },
                    {
                        "title": "Все пользователи", # это для текста в левом меню
                        "icon": "Account_Child", # это для иконки в левом меню
                        "link": reverse_lazy("admin:auth_user_changelist") # это для ссылки в левом меню
                    },
                ]
            },
            {
                "title": "Управление магазином", # это для текста в левом меню
                "separator": True, # это для разделителя в левом меню
                "collapsible": False, # это для скрытия в левом меню
                "items": [
                    {
                        "title": "Продукты", # это для текста в левом меню
                        "icon": "Box", # это для иконки в левом меню
                        "link": reverse_lazy("admin:appShop_product_changelist") # это для ссылки в левом меню
                    },
                    {
                        "title": "Категории", # это для текста в левом меню
                        "icon": "Category", # это для иконки в левом меню
                        "link": reverse_lazy("admin:appShop_category_changelist") # это для ссылки в левом меню
                    }
                ]
            }
        ]
    },
        "COLORS": {
        "base": {
            "50": "249, 250, 251",
            "100": "243, 244, 246",
            "200": "229, 231, 235",
            "300": "209, 213, 219",
            "400": "156, 163, 175",
            "500": "107, 114, 128",
            "600": "75, 85, 99",
            "700": "55, 65, 81",
            "800": "31, 41, 55",
            "900": "17, 24, 39",
            "950": "3, 7, 18",
        },
        "primary": {
            "50": "240, 253, 244",
            "100": "225, 245, 237",
            "200": "191, 231, 214",
            "300": "152, 214, 182",
            "400": "108, 187, 146",
            "500": "74, 163, 118",
            "600": "51, 131, 95",
            "700": "41, 107, 78",
            "800": "34, 88, 65",
            "900": "28, 70, 53",
            "950": "19, 48, 37"
        },
        "font": {
            "subtle-light": "var(--color-base-500)",  # text-base-500
            "subtle-dark": "var(--color-base-400)",  # text-base-400
            "default-light": "var(--color-base-600)",  # text-base-600
            "default-dark": "var(--color-base-300)",  # text-base-300
            "important-light": "var(--color-base-900)",  # text-base-900
            "important-dark": "var(--color-base-100)",  # text-base-100
        },
    },
}

CURRENCIES = ('RUB', 'USD', 'EUR')
CURRENCY_CHOICES = [('RUB', 'RUB ₽'), ('USD', 'USD $'), ('EUR', 'EUR €')]